services:
  mysql:
    image: mysql:8.0
    container_name: container_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: decoration
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: container_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "5051:80"
    depends_on:
      - mysql

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: decoration_container_php_
    restart: always
    volumes:
      - ./project:/var/www/html/
      - ./php/php.ini:/usr/local/etc/php/php.ini  # Monte php.ini dans le conteneur

    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data: